[theme]

# Primary accent for interactive elements
primaryColor = '#75B8E3'

# Background color for the main content area
backgroundColor = '#C1DFE3'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#93DAE3'

# Color used for almost all text
textColor = '#1E1D1D'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"